### ISSUE TITLE
project link can't be opened

### ISSUE THREAD

**Issue by mmaslano** [IBM/liz#2] opened 2024-10-29 15:00 UTC
**Describe the bug**
I was able to use your web twice for creating an installation helper, but now it gives me only the error.

  ***Error Details***
  Status code: none
  Status message: none
  Error code: document.getElementById(...) is null

  ***Error Stack***
  ga</<@https://ibm.github.io/liz/assets/index-BLUz-j_C.js:1:11356
af@https://ibm.github.io/liz/assets/vendor-AXNh4UrT.js:40:24283
il@https://ibm.github.io/liz/assets/vendor-AXNh4UrT.js:40:42411
ab@https://ibm.github.io/liz/assets/vendor-AXNh4UrT.js:40:36625
Pa@https://ibm.github.io/liz/assets/vendor-AXNh4UrT.js:38:3279
f5@https://ibm.github.io/liz/assets/vendor-AXNh4UrT.js:40:41286
Ua@https://ibm.github.io/liz/assets/vendor-AXNh4UrT.js:40:40278
_T@https://ibm.github.io/liz/assets/vendor-AXNh4UrT.js:40:35735
$@https://ibm.github.io/liz/assets/vendor-AXNh4UrT.js:25:1536
W@https://ibm.github.io/liz/assets/vendor-AXNh4UrT.js:25:1894

  
  **To Reproduce**
  1. Try out installer helper twice.
  2. Click on the top and try again
  3. See error
  
  **Expected behaviour**
  
  **Screenshots**
  
  **Desktop (please complete the following information):**
   - Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0
  
  **Additional context**

**Comment by modean** [comment] 2024-10-30 12:48
@mmaslano can you clarify on what is meant by `Click on the top and try again`? Does it simply mean that the app bails out with the above exception as soon as you try to access https://ibm.github.io/liz/ ?

**Comment by mmaslano** [comment] 2024-10-30 12:57
Yes, as soon as I try to access https://ibm.github.io/liz/ (By on the top I meant click on the left top name of the app "Installation assistant for LInux...").

**Comment by modean** [comment] 2024-10-31 12:55
Closing cause as per issue https://github.com/IBM/liz/issues/3 the stack trace from above seems to be gone. Also I was not able to reproduce the stack trace using either Chrome or Firefox.

**Closed as completed by modean** 2024-10-31 12:55 UTC
